# tutaj można dodać komentarz
start_path: C:/Users/Dell/Desktop/Jezyki Skryptowe lab/Projekt/start
text_path: C:/Users/Dell/Desktop/Jezyki Skryptowe lab/Projekt/text
data_path: C:/Users/Dell/Desktop/Jezyki Skryptowe lab/Projekt/data
others_path: C:/Users/Dell/Desktop/Jezyki Skryptowe lab/Projekt/others
max_number_of_files: 5