# extensions that my program can control
extensions:
   - txt
   - csv
   - docx
   - pdf
   - xlsx

#if the file name contain folder name, then it is moved to this folder
important_folders:
   - PWr

#folder names
folder_names:
   - text
   - data
   - others
   - PWr

#paths of folders used
start: C:/Users/Dell/Desktop/Jezyki Skryptowe lab/Projekt/start
text: C:/Users/Dell/Desktop/Jezyki Skryptowe lab/Projekt/text
data: C:/Users/Dell/Desktop/Jezyki Skryptowe lab/Projekt/data
others: C:/Users/Dell/Desktop/Jezyki Skryptowe lab/Projekt/others

#paths for extensions
txt: C:/Users/Dell/Desktop/Jezyki Skryptowe lab/Projekt/text
docx: C:/Users/Dell/Desktop/Jezyki Skryptowe lab/Projekt/text
pdf: C:/Users/Dell/Desktop/Jezyki Skryptowe lab/Projekt/text
csv: C:/Users/Dell/Desktop/Jezyki Skryptowe lab/Projekt/data
xlsx: C:/Users/Dell/Desktop/Jezyki Skryptowe lab/Projekt/data

#paths for names
PWr: C:/Users/Dell/Desktop/Jezyki Skryptowe lab/Projekt/PWr

#max number of files in folder
max_number_of_files: 10

#max file size in bytes
max_size_of_file: 30000