parent_directory:
   - C:/Users/Dell/Desktop/Jezyki Skryptowe lab/Projekt

extensions:
   - txt
   - csv
   - docx
   - pdf
   - xlsx

by_names:
   - PWr

folder_names:
   - text
   - data
   - others
   - PWr

start:
   - C:/Users/Dell/Desktop/Jezyki Skryptowe lab/Projekt/start

text:
   - C:/Users/Dell/Desktop/Jezyki Skryptowe lab/Projekt/text

data:
   - C:/Users/Dell/Desktop/Jezyki Skryptowe lab/Projekt/data

others:
   - C:/Users/Dell/Desktop/Jezyki Skryptowe lab/Projekt/others

txt:
   - C:/Users/Dell/Desktop/Jezyki Skryptowe lab/Projekt/text

docx:
   - C:/Users/Dell/Desktop/Jezyki Skryptowe lab/Projekt/text

pdf:
   - C:/Users/Dell/Desktop/Jezyki Skryptowe lab/Projekt/text

csv:
   - C:/Users/Dell/Desktop/Jezyki Skryptowe lab/Projekt/data

xlsx:
   - C:/Users/Dell/Desktop/Jezyki Skryptowe lab/Projekt/data

PWr:
   - C:/Users/Dell/Desktop/Jezyki Skryptowe lab/Projekt/PWr

max_number_of_files:
   - 10

max_size_of_file:
   - 30000

